# Generated by Django 3.1.2 on 2020-10-29 20:41

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precipitacao',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempertura',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticias',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('realizacao', ckeditor.fields.RichTextField()),
                ('foto', ckeditor_uploader.fields.RichTextUploadingField()),
                ('lattes', models.CharField(max_length=100, unique=True)),
                ('facebook', models.CharField(max_length=100, unique=True)),
                ('instagram', models.CharField(max_length=100, unique=True)),
                ('linkedin', models.CharField(max_length=100, unique=True)),
                ('data', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
