# Generated by Django 3.1.2 on 2020-11-01 17:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem',
            new_name='imagem_pluviograma',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='imagem_precipitacao',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='imagem_queimada',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='imagem_temperatura',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('imagem', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data', models.DateTimeField()),
                ('publicar', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
