# Generated by Django 3.1.2 on 2020-11-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_imagens_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
