# Generated by Django 3.1.2 on 2020-11-02 13:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201102_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_pluviograma',
            new_name='imagem_01',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_precipitacao',
            new_name='imagem_02',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_queimada',
            new_name='imagem_03',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_temperatura',
            new_name='imagem_04',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='imagem_05',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
