# Generated by Django 3.1.2 on 2020-11-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201102_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_01',
            new_name='imagem_mini_post',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_02',
            new_name='imagem_post_01',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_03',
            new_name='imagem_post_02',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_04',
            new_name='imagem_post_04',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_05',
            new_name='imagem_post_05',
        ),
    ]
