# Generated by Django 3.1.2 on 2020-11-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201102_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_mini_post',
            new_name='imagem_mini_post_01',
        ),
    ]
