# Generated by Django 3.1.2 on 2020-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201102_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_post_05',
            new_name='imagem_post_03',
        ),
    ]
