# Generated by Django 3.1.2 on 2020-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201102_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='imagem_mini_post_01',
            new_name='imagem_post',
        ),
        migrations.RenameField(
            model_name='pluviograma',
            old_name='imagem',
            new_name='imagem_mini_post',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='imagem_post_01',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='imagem_post_02',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='imagem_post_03',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='imagem_post_04',
        ),
        migrations.RemoveField(
            model_name='pluviograma',
            name='resumo',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='fonte',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pluviograma',
            name='fonte',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='fonte',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetos',
            name='url',
            field=models.URLField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
