# Generated by Django 3.1.2 on 2020-11-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201103_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='fonte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pluviograma',
            name='fonte',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
