# Generated by Django 3.1.2 on 2020-11-04 20:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201103_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=800, unique=True)),
                ('texto', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
